In [1]:
import pandas as pd
from faker import Faker

In [2]:
fake = Faker()

---

In [3]:
df = pd.DataFrame({
    'name': [fake.first_name() for _ in range(3)],
    'age': [fake.random_number(digits=2) for _ in range(3)]
})

In [4]:
df.head()

       name  age
0     Karen   20
1   Tiffany   30
2  Michelle   48

### apply - DataFrame lever

##### row axis

In [5]:
series = df.apply(lambda row: row['age'] / 10, axis=1)
series.to_frame(name='age')

   age
0  2.0
1  3.0
2  4.8

##### column axis

In [6]:
df.apply(lambda column: column.sum(), axis=0)

name    KarenTiffanyMichelle
age                       98
dtype: object

### transform - column level

In [7]:
df['age'].transform(lambda age: age / 10)

0    2.0
1    3.0
2    4.8
Name: age, dtype: float64

### Map

In [8]:
df['age'].map(lambda age: age / 10)

0    2.0
1    3.0
2    4.8
Name: age, dtype: float64