In [1]:
import pandas as pd
from faker import Faker

In [2]:
fake = Faker()

---

In [3]:
name_age_df = pd.DataFrame({
    'name': ['John', 'Mark'] + ['Barbie'],
    'age': [fake.random_number(digits=2) for _ in range(3)]
})

name_phone_df = pd.DataFrame({
    'name': ['Mark', 'John'] + ['Ken'],
    'phone': [fake.phone_number() for _ in range(3)]
})

### Join

In [11]:
name_age_df.join(name_phone_df.set_index('name'), on='name', how='left').head() # set_index to prevent error: You are trying to merge on str and int64 columns for key 'name'

     name  age                   phone
0    John    9        001-870-591-3524
1    Mark   15  001-828-784-1969x10859
2  Barbie   18                     NaN

### merge

##### inner

In [4]:
merged_df= name_age_df.merge(name_phone_df, on='name').head()

##### left

In [5]:
name_phone_df['phone'] = name_phone_df['phone'].transform(lambda phone: fake.phone_number())

In [6]:
merged_df.merge(name_phone_df, on='name', how='left', suffixes=['_old', '_new']).head()

   name  age         phone_old               phone_new
0  John    8      659-368-3953        001-870-591-3524
1  Mark   14  537-630-2830x164  001-828-784-1969x10859

##### right

In [7]:
name_age_df['age'] = name_age_df['age'].transform(lambda age: age + 1)

In [8]:
merged_df.merge(name_age_df, on='name', how='right', suffixes=['_old', '_new']).head()

     name  age_old             phone  age_new
0    John      8.0      659-368-3953        9
1    Mark     14.0  537-630-2830x164       15
2  Barbie      NaN               NaN       18